### ISSUE TITLE
tell us what changes were made in new releases to cran

### ISSUE THREAD

**Issue by sckott** [ropenscilabs/robotstxt#14]
can you please list what changes were made with each new release to cran 

e.g., looking at https://github.com/ropenscilabs/robotstxt/compare/CRAN-v0.1.2...v0.3.2?w=1 I see what I think are lots of changes, and they aren't mentioned in NEWS or in releases here. 

something like this https://github.com/hadley/dplyr/releases/tag/v0.5.0 is a good example

**Comment by petermeissner** [comment]
Uh, I will take some minutes this week and fill in the blanks.

**Comment by petermeissner** [comment]
done (as good as possible 6 months after last looking at the code base): https://github.com/ropenscilabs/robotstxt/commit/6f146bb2f3e635bac8772fd6cf7d33e8054aa014
