### ISSUE TITLE
Please use git tags and releases

### ISSUE THREAD

**Issue by sckott** [ropenscilabs/robotstxt#20]
hi 👋  

We want all rOpenSci pkgs to consistently keep track of changes. You already use NEWS.md, thanks for that. Please also do the following:

- git tag each CRAN version - you've git tagged some, but not all cran versions. To git tag commits for previous CRAN versions, you can find the commit, then do e.g., `git tag -a v1.2 9fceb02` where `9fceb02` is the commit sha
- use the [releases tab](https://github.com/ropensci/biomartr/releases) in this repo to include the associated NEWS items for each tag/version, e.g., see https://github.com/ropensci/taxize/releases/tag/v0.8.8 - you've already done this, but please continue to do so. 

Can you please do the two above items from now on?

**Comment by petermeissner** [comment]
jip, will do / have done.
