### ISSUE TITLE
use release notes

### ISSUE THREAD

**Issue by sckott** [ropenscilabs/robotstxt#21]
Hi @petermeissner can you put your NEWS items in your release notes https://github.com/ropenscilabs/robotstxt/releases - looks like you were doing it before but haven't in the last few. thanks

**Comment by petermeissner** [comment]
Thanks for keeping an eye on repo quality ... 

I did not draft a release for version v0.5.2 yet - that has been done now and the notes from the NEWS file are included. 

The other 'releases' in between are merely version tags and I will not add any text to them.
